blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('search_ct/', views.search_ct, name='search-ct'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('enroll/<slug:slug>/', views.PostEnroll.as_view(), name='post_enroll'),  # noqa

]

pp4clinicaltrials/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))
GENDER = ((0, "All"), (1, "Male"), (2, "Female"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipe_post", default=0)
    IRB_number = models.CharField(max_length=200, default=101)
    prin_invest = models.CharField(max_length=200, default='name')
    contact_name = models.CharField(
        max_length=400, unique=False, default='name')
    contact_email = models.CharField(
        max_length=200, unique=False, default='null')
    primary_disease = models.CharField(max_length=5000, blank=True)
    eligible_age_min = models.IntegerField(blank=False, default=0)
    eligible_age_max = models.IntegerField(blank=False, default=100)
    gender = models.IntegerField(choices=GENDER, default=0)
    main_image = CloudinaryField('image', default='placeholder')
    content = models.CharField(max_length=5000, blank=True)
    no_participants = models.ManyToManyField(
        User, related_name='ct_no_participants', blank=True)
    status = models.IntegerField(choices=STATUS, default=0)
    start_dt = models.DateField(default='2022-09-22')
    end_dt = models.DateField(default='2022-09-22')
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    # tag = models.ManyToManyField(Tags, related_name='tags', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def no_enrolled(self):
        return self.no_participants.count()


class Question(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="questions")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Question {self.body} by {self.name}"


# class Tags(models.Model):
#     name = models.CharField(max_length=80, unique=True)

#     class Meta:
#         ordering = ["name"]

#     def __str__(self):
#         return self.name

blog/forms.py
from .models import Question
from django import forms


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Post
from .forms import QuestionForm


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 5


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        questions = post.questions.filter(approved=True).order_by("-created_on")  # noqa
        enrolled = False
        if post.no_participants.filter(id=self.request.user.id).exists():
            enrolled = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "questions": questions,
                "asked": False,
                "enrolled": enrolled,
                "question_form": QuestionForm()
            }
        )

    def post(self, request, slug, *args, **kwargs):

        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        questions = post.questions.filter(approved=True).order_by("-created_on")  # noqa
        enrolled = False
        if post.no_participants.filter(id=self.request.user.id).exists():
            enrolled = True
        question_form = QuestionForm(data=request.POST)
        if question_form.is_valid():
            question_form.instance.email = request.user.email
            question_form.instance.name = request.user.username
            question = question_form.save(commit=False)
            question.post = post
            question.save()
        else:
            question_form = QuestionForm()

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "questions": questions,
                "asked": True,
                "question_form": question_form,
                "enrolled": enrolled,
            },
        )


class PostEnroll(View):

    def post(self, request, slug, *args, **kwargs):
        post = get_object_or_404(Post, slug=slug)
        if post.no_participants.filter(id=request.user.id).exists():
            post.no_participants.remove(request.user)
        else:
            post.no_participants.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def search_ct(request):
    if request.method == "POST":
        searched = request.POST['searched']
        search_post = Post.objects.filter(primary_disease__contains=searched)

        return render(
            request,
            "search_ct.html",
            {
                'searched': searched,
                'search_post': search_post
            },
        )
    else:
        return render(
            request,
            "search_ct.html",
            {
            },
        )

templates/base.html
{% load static %}


<!DOCTYPE html>
<html class="h-100" lang=en>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clinical Trials</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
        type='text/css'>
    <link
        href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
        rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    {% block extra_css %}
    {% endblock %}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">NYC Hospital</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="search-container">
                <form class="input-group" method="POST" action="{% url 'search-ct' %}">

                    {% csrf_token %}

                    <input class="form-control" type="text" placeholder="Search by Disease" name="searched">
                    <button type="submit" id="button-search"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>


    </nav>

    </div>
    <main>
        {% if messages %}
        <div class="container alert alert-success" id="msg">
            <strong>Messages:</strong>
            <ul>
                {% for message in messages %}
                <li>{{message}}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% block content %}
        {% endblock content%}
    </main>
    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://facebook.com/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">@2022</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.0.slim.js"
        integrity="sha256-milezx5lakrZu0OP9b2QWFy1ft/UEUK6NH1Jqz8hUhQ=" crossorigin="anonymous"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<!-- Page Header -->
<header class="masthead"> 
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Clinical Trials at NYC Hospital</h1>
                    <span class="subheading">Participating in our clinical trials gives you access to the latest
                        treatments and helps improve for generations to come</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% for post in post_list %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Main Content -->

            <!-- Content Goes here -->

            <div class="container">
                <!-- Post preview-->
                <div class="post-preview">
                    
                    <a href="{% url 'post_detail' post.slug %}">
                        <h2 class="post-title">{{ post.title }}</h2>
                    </a>
                    <div class="row">
                        <div class="col-lg-4 col-md-4 post-meta">
                            <p class="post-meta">
                                <b>Diseases:</b> {{ post.primary_disease }}
                            </p>
                        </div>
                        <div class="col-lg-4 col-md-4 post-meta">
                            <p class="post-meta">
                            <b>Age:</b> {{ post.eligible_age_min }} - {{ post.eligible_age_max }}
                            </p>
                        </div>
                        <div class="col-lg-4 col-md-4 post-meta gender">
                            <p class="post-meta">
                            <b>Gender:</b> {{ post.get_gender_display }}
                            </p>
                        </div>

                    </div>
                </div>
            </div>
            
            <hr class="my-4">
        </div>
    </div>
   
</div>
<!-- Divider-->


{% endfor %}

{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

        {% endif %}
    </ul>
</nav>
{% endif %}


{%endblock%}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}

<body>

  <!-- Page content-->
  <div class="container mt-5">
    <div class="row">
      <div class="col">
        <!-- Post content-->
        <article>
          <!-- Post header-->
          <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1 ">{{post.title}}</h1>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">{{post.excerpt}}</div>
          </header>
          <!-- Preview image figure-->
          {% if "placeholder" in post.main_image.url %}
          <figure class="mb-0"><img class="card-img-top" 
            src="https://res.cloudinary.com/dzmhuvuj3/image/upload/v1668094680/static/img/base_header_pic.40665af3d4dd.jpg" 
            alt="post-image-default"></figure>

          {% else %}
          <figure class="mb-0"><img class="figure-img img-fluid rounded" src=" {{ post.main_image.url }} "
              alt="post_image"></figure>
          {% endif %}
          <!-- Post content-->
          <section class="mb-5">
            <div class="row">
              <div class="col-lg-6 col-md-6">
                <p><b>Principal Investigator:</b> {{post.prin_invest}}</p>
              </div>
              <div class="col-lg-6 col-md-6">
                <p><b>IRB Number:</b> {{post.IRB_number}}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6 col-md-6">
                <p><b>Contact Name:</b> {{post.contact_name}}</p>
              </div>
              <div class="col-lg-6 col-md-6">
                <p><b>Email:</b> {{post.contact_email}}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6 col-md-6">
                <p><b>Age:</b> {{post.eligible_age_min}} - {{post.eligible_age_max}}</p>
              </div>
              <div class="col-lg-6 col-md-6">
                <p><b>Gender:</b> {{post.get_gender_display}}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6 col-md-6 mx-auto">
                <p><b>Start Date:</b> {{post.start_dt}}</p>
              </div>
              <div class="col-lg-6 col-md-6 mx-auto">
                <p><b>End Date:</b> {{post.end_dt}}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 col-md-12 mx-auto">
                <p><b>Diseases:</b> {{ post.primary_disease }}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 col-md-12 mx-auto">
                <p>{{post.content | safe }}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-6">
                <strong>
                  {% if user.is_authenticated %}
                  <form class="d-inline" action="{% url 'post_enroll' post.slug %}" method="POST">
                    {% csrf_token %}
                    {% if enrolled %}
                    <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"
                      style="color: red">Leave</button>
                    {% else %}
                    <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"
                      style="color: blue">Enroll</button>
                    {% endif %}
                  </form>
                  {% else %}
                  <span class="text-secondary"></span>
                  {% endif %}
                  <!-- The number of likes goes before the closing strong tag -->
                  <span class="text-secondary">Number of participants currently enrolled: {{ post.no_enrolled }} </span>
                </strong>
              </div>
            </div>
          </section>
          <section class="mb-5">
            <div class="card bg-light">
              <div class="card-body">
                <h3>Questions:</h3>
                {% if asked %}
                <div class="alert alert-success" role="alert">
                  Your question is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}
                <p>Posting as: {{ user.username }}</p>
                <form method="post" class="mb-4">
                  {{ question_form | crispy }}
                  {% csrf_token %}
                  <button type="submit" class="btn-like">Submit</button>
                </form>
                {% endif %}
                {% endif %}
                <!--question-->
                <div class="d-flex">
                  <div class="ms-3">
                    {% for question in questions %}
                    <div class="questions" style="padding: 10px;">
                      <p class="font-weight-bold">
                        <!-- The questioner's name goes here. Check the model if you're not sure what that is -->
                        {{ question.name }}
                        <span class=" text-muted font-weight-normal">
                          <!-- The question's created date goes here -->
                          {{ question.created_on }}
                        </span> wrote:
                      </p>
                      <!-- The body of the question goes before the | -->
                      {{ question.body | linebreaks }}
                    </div>
                    <!-- Our for loop ends here -->
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </section>
        </article>
      </div>
    </div>
  </div>

</body>

{% endblock content %}

templates/search_ct.html
{% extends "base.html" %}

{% block content %}

{% if searched %}



{% for post in search_post %}

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="container">
                <h4>Search Results for "{{ searched }}"</h4>
                <hr>
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'post_detail' post.slug %}">
                        <h2 class="post-title">{{ post.title }}</h2>
                    </a>
                    <div class="row">
                        <div class="col-lg-4 col-md-4 post-meta ">
                            <p class="post-meta">
                                <b>Diseases:</b> {{ post.primary_disease }}
                            </p>
                        </div>
                        <div class="col-lg-4 col-md-4 post-meta ">
                            <p class="post-meta">
                                <b>Age:</b> {{ post.eligible_age_min }} - {{ post.eligible_age_max }}
                            </p>
                        </div>
                        <div class="col-lg-4 col-md-4 post-meta gender">
                            <p class="post-meta">
                                <b>Gender:</b> {{post.get_gender_display}}
                            </p>
                        </div>

                    </div>
                </div>
            </div>
            <hr class="my-4">
        </div>
    </div>

</div>
{% empty %}
</br>
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="container">
                <h2 class="post-title">No trials found. Please search another disease site</h2>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="container">
                <h2 class="post-title">Please enter a disease to search</h2>
            </div>
        </div>
    </div>
</div>
{% endif %}




{%endblock%}